### ISSUE TITLE
Trace information for failed tests

### ISSUE THREAD

**Issue by svenax** [quangson91/intellij_rest_cli#23]
Hi! This tool is getting better and better by the day!

When a test fails, it would be nice if you could write e.g. file and line to the junit report to make it easier to identify where the failure occurred. This is what you get from PHPUnit - something similar would be nice.

<img width="745" alt="CleanShot 2020-08-18 at 15 04 29@2x" src="https://user-images.githubusercontent.com/8472/90516887-ee58d600-e164-11ea-92da-944715ec2965.png">

At least for Gitlab, all JUnit files will be integrated into the same display, so having the file name in the error text is still useful.

**Comment by quangson91** [comment]
That's a great idea.
I will add that information in the test report.

Thanks!

**Comment by quangson91** [comment]
Hi @svenax,
Currently in the parser we only know the block of test script. For example:
```
### Successful test: check response status is 200
1. GET https://httpbin.org/status/200
2. 
3. > {%
4. client.test("Request executed successfully", function() {
5.   client.assert(response.status === 200, "Response status is not 200");
6. });
7. %}

```
If the test line [5] is failed.
we just know, the line in the begning of the test script (which is line [3]).
Is that information still userful?
How do you think?

**Comment by quangson91** [comment]
I fixed this problem.
Please check the demo at: https://gitlab.com/quangson91/demo_intellij_rest_cli/-/pipelines/179322650/test_report

<img width="1079" alt="Screen Shot 2020-08-19 at 12 16 31 AM" src="https://user-images.githubusercontent.com/6185205/90544362-3e5d8a00-e1b1-11ea-8dcb-c5e6c6bc3a7f.png">

If you have any ideas to suggest for this feature, please re-open this issue to discussion :) 
Thank you so much!

**Comment by svenax** [comment]
Great works! Thank you.

Do uou think you could format the result as in the example above thoug, e.g. *full-path:line*. Most editors can understand that format and jump directly to the correct spot.

**Comment by quangson91** [comment]
I think it is possible. Let me try :)
