### ISSUE TITLE
Bug with varible replacement via {{var}}

### ISSUE THREAD

**Issue by martinqvistgard** [quangson91/intellij_rest_cli#5]
There seems to be a problem with variable replacement via {{var}}, at least for variables that are defined by response handler scripts.

Test script as below:

```js
POST http://127.0.0.1:81/en/api/auth/login
Content-Type: application/json;charset=UTF-8
Accept: application/json

{"username":"xxxx","password":"qwerty"}

> {%
client.test("That there is a value for the auth token", function() {
    client.assert(false, 'token is ' + response.headers.valueOf('Authorization'));
});

client.global.set("auth_token", response.headers.valueOf('Authorization'));
%}

###

GET http://127.0.0.1:81/en/api/auth/config
Content-Type: application/json;charset=UTF-8
Accept: application/json
Authorization: {{auth_token}}

> {%
client.test("That logged in user gets information", function() {
    client.assert(response.body.isLoggedIn === true, "User is not logged in, despite supplying auth token");
});

client.test("That auth_token still has a value", function() {
    client.assert(false, client.global.get('auth_token'));
});
%}
```

This is my output from the second test in php storm
![image](https://user-images.githubusercontent.com/703595/89261035-ab0f4b00-d62d-11ea-864a-e1214b57293f.png)

This is the output from cli-runner:

```
WARNING: Define auth_token but there is no define in environment                      
                                                                                      
__________________________________________________                                    
                                                                                      
##### Execute request http://127.0.0.1:81/en/api/auth/login #####       
>>> Test script >>>                                                                   
✓ That request was successful                                                         
✓ That Authorization token was returned
✗ That there is a value for the auth token
token is Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
<<< Test script <<<

__________________________________________________

##### Execute request http://127.0.0.1:81/en/api/auth/config #####
>>> Test script >>>
✗ That logged in user gets information
User is not logged in, despite supplying auth token
✗ That auth_token still has a value
Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9
<<< Test script <<<
```

As you can see, cli-runner trows a warning about auth_token and also the authorization fails.
Running cli-runner with full logs gives this line
```
Aug 04, 2020 8:42:57 AM uos.dev.restcli.executor.OkhttpRequestExecutor$CustomLogger log 
INFO: Authorization: {{auth_token}}     
```

**Comment by quangson91** [comment]
Thank you for the very detailed report.

Currently, the variables replacement is supported replace from http-client.env.json.

But replace variables are defined by response handler scripts that are able to replace.
I will fix this issue today.

Thank you!

**Comment by quangson91** [comment]
@martinqvistgard I fixed this issue.
You can check the latest release.
https://github.com/quangson91/intellij_rest_cli/actions/runs/194934387

Or in the release tab:
https://github.com/quangson91/intellij_rest_cli/releases/tag/v1.2

Please take a look when you have time :) 

Thank you!

**Comment by martinqvistgard** [comment]
Just tried my test script and it now works flawlessly!
Thanks! :1st_place_medal:

**Comment by quangson91** [comment]
Great.
If you need any support or request add any features that file an issue :) 
we will discuss and implement it.

So, I will close this issue.

Thank you so much!
